# Generated by Django 4.0.3 on 2022-03-13 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('screenshot', models.ImageField(upload_to='', verbose_name='images')),
                ('posted_at', models.DateField(auto_now_add=True)),
                ('repository_link', models.CharField(blank=True, max_length=200)),
                ('live_link', models.CharField(blank=True, max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='awards.profile')),
            ],
        ),
    ]
