# Generated by Django 4.0.3 on 2022-03-13 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=1000)),
                ('visuals_rating', models.PositiveBigIntegerField(default=10)),
                ('functionality_rating', models.PositiveBigIntegerField(default=10)),
                ('content_rating', models.PositiveBigIntegerField(default=10)),
                ('usability_rating', models.PositiveBigIntegerField(default=10)),
                ('review_date', models.DateField(auto_now_add=True)),
                ('Project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='awards.project')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='awards.profile')),
            ],
        ),
    ]
