# Generated by Django 4.0.3 on 2022-03-13 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['posted_at']},
        ),
    ]
